# docker system prune -a -f && docker volume prune -f && docker network prune -f && docker container prune -f
 
 services:

  redisdb:
    image: redis:7.4.1
    container_name: redis-DEPLOY
    restart: always
    ports:
      - 6377:6379
    volumes:
      - /data
  
  redis-commander:
    image: rediscommander/redis-commander:v0.9.0
    container_name: redis-commander
    restart: always
    hostname: redis-commander
    depends_on:
      - redisdb
    environment:
    - REDIS_HOSTS=local:redis-DEPLOY:6377
    ports:
    - 9081:8081
