name: Sanbox Dispatch ⚡
run-name: "${{ github.actor }} - ${{ github.run_id }}"

on:
  push:
    branches:
      - main
      - develop
    types:
      - closed
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docker/**'
      - 'docs/**'
      - 'src/**/_requests/**'
  workflow_dispatch:
    inputs:
      buildMode:
        description: "Qual ação deseja fazer?"
        required: false
        default: Build
        type: choice
        options:
          - Build
          - Build + Tag Validation
      environment:
        description: 'Qual ambiente deseja fazer o deploy?'
        required: true
        type: environment
      gitLeaks:
        type: boolean
        description: 'Run GitLeaks'
        required: false
        default: true
      sonarQube:
        type: boolean
        description: 'Run SonarQube'
        required: false
        default: true
      tests:
        type: boolean
        description: 'Run Unit & Integration Tests'
        required: false
        default: true
      snyk:
        type: boolean
        description: 'Snyk.io'
        required: false
        default: true
      msgCanalDeploy:
        type: string
        description: 'Message to be displayed in the summary'
        required: false
        default: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'

jobs:
  call-reusable-workflow:
    uses: felipementel/reusable-workflows/.github/workflows/sandbox-api.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      buildMode: ${{ inputs.buildMode }}
      environment: ${{ inputs.environment }}
      gitLeaks: ${{ inputs.gitLeaks }}
      sonarQube: ${{ inputs.sonarQube }}
      testsFolder: "" # "tests"
      tests: false # ${{ inputs.tests }}
      snyk: ${{ inputs.snyk }}
      msgCanalDeploy: ${{ inputs.msgCanalDeploy }}
      dotnetVersion: ${{ vars.DOTNETVERSION }}
      projectBaseDir: ${{ vars.PROJECTBASEDIR }}
      solutionFileName: ${{ vars.SOLUTIONFILENAME }}
      mainProject: ${{ vars.MAINPROJECT }}
      reportTitle: ${{ vars.REPORTTITLE }}
      sonarExclusions: ${{ vars.SONAREXCLUSIONS || ''}}
      imageName: ${{ vars.IMAGENAME }}-sandbox
      openAPIFolder: "" # "open-api"
    secrets:
      inherit
